Script started on Wed 07 Nov 2012 12:25:35 PM PST
[?1034hbash-4.1$ valgrind --leak-check=full \
> list4 foo bar baz qux
==10520== Memcheck, a memory error detector
==10520== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==10520== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==10520== Command: list4 foo bar baz qux
==10520== 
0x4c23180->node {word=0x7ff000605->[qux], link=0x4c23130}
0x4c23130->node {word=0x7ff000601->[baz], link=0x4c230e0}
0x4c230e0->node {word=0x7ff0005fd->[bar], link=0x4c23090}
0x4c23090->node {word=0x7ff0005f9->[foo], link=0x4c23040}
==10520== 
==10520== HEAP SUMMARY:
==10520==     in use at exit: 0 bytes in 0 blocks
==10520==   total heap usage: 5 allocs, 5 frees, 80 bytes allocated
==10520== 
==10520== All heap blocks were freed -- no leaks are possible
==10520== 
==10520== For counts of detected and suppressed errors, rerun with: -v
==10520== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 6 from 6)
bash-4.1$ echo $?
9
bash-4.1$ exit
exit

Script done on Wed 07 Nov 2012 12:26:43 PM PST
