Script started on Wed 07 Nov 2012 11:51:08 AM PST
[?1034hbash-4.1$ valgrind --leak-check=full \
> list3 foo bar baz qux
==4876== Memcheck, a memory error detector
==4876== Copyright (C) 2002-2010, and GNU GPL'd, by Julian Seward et al.
==4876== Using Valgrind-3.6.0 and LibVEX; rerun with -h for copyright info
==4876== Command: list3 foo bar baz qux
==4876== 
0x4c23180->node {word=0x7ff000605->[qux], link=0x4c23130}
0x4c23130->node {word=0x7ff000601->[baz], link=0x4c230e0}
0x4c230e0->node {word=0x7ff0005fd->[bar], link=0x4c23090}
0x4c23090->node {word=0x7ff0005f9->[foo], link=0x4c23040}
==4876== 
==4876== HEAP SUMMARY:
==4876==     in use at exit: 80 bytes in 5 blocks
==4876==   total heap usage: 5 allocs, 0 frees, 80 bytes allocated
==4876== 
==4876== 80 (16 direct, 64 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==4876==    at 0x4A05FDE: malloc (vg_replace_malloc.c:236)
==4876==    by 0x4005BE: main (list3.c:17)
==4876== 
==4876== LEAK SUMMARY:
==4876==    definitely lost: 16 bytes in 1 blocks
==4876==    indirectly lost: 64 bytes in 4 blocks
==4876==      possibly lost: 0 bytes in 0 blocks
==4876==    still reachable: 0 bytes in 0 blocks
==4876==         suppressed: 0 bytes in 0 blocks
==4876== 
==4876== For counts of detected and suppressed errors, rerun with: -v
==4876== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 6 from 6)
bash-4.1$ exit
exit

Script done on Wed 07 Nov 2012 11:52:21 AM PST
