Script started on Tue 06 Nov 2012 12:03:48 PM PST
[?1034hbash-4.1$ gdb uninit
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux (7.2-50.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /afs/cats.ucsc.edu/users/n/aaguil10/Documents/CMPS12B/Labs/Lab5/uninit...done.
(gdb) break main
Breakpoint 1 at 0x400503: file uninit.c, line 8.
(gdb) run
Starting program: /afs/cats.ucsc.edu/users/n/aaguil10/Documents/CMPS12B/Labs/Lab5/uninit 

Breakpoint 1, main (argc=1, argv=0x7fffffffe338) at uninit.c:8
8	   printf ("%d\n", foo);
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.47.el6_2.12.x86_64
(gdb) print foo
$1 = 32767
(gdb) step
32767
10	   printf ("%d\n", *pointer);
(gdb) print pointer
$2 = (int *) 0x0
(gdb) step

Program received signal SIGSEGV, Segmentation fault.
0x000000000040051e in main (argc=1, argv=0x7fffffffe338) at uninit.c:10
10	   printf ("%d\n", *pointer);
(gdb) quit
A debugging session is active.

	Inferior 1 [process 17051] will be killed.

Quit anyway? (y or n) y
bash-4.1$ exit
exit

Script done on Tue 06 Nov 2012 12:04:57 PM PST
